spring.application.name=CRUD
server.port=8080

# ===============================
# DATASOURCE (SUPABASE - POSTGRES)
# ===============================

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.bszuynlbytdvphfxiazv
spring.datasource.password=Huv24EbY9nADn9C1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

#  spring mailer

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=uppalmuskan268@gmail.com
spring.mail.password=kylo tcmy xxlb ggwk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



supabase.url=https://bszuynlbytdvphfxiazv.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzenV5bmxieXRkdnBoZnhpYXp2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDYxMTc1MywiZXhwIjoyMDg2MTg3NzUzfQ.IBBwo38KKZbG2qk9vlMwca10jA4KqL-MSTYKAiCyIHU
supabase.bucket=Public_media

# ===============================
# OAUTH2 CLIENT CONFIGURATION
# ===============================
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET
spring.security.oauth2.client.registration.github.scope=read:user,user:email

